### ISSUE TITLE
check SBLGNT corrections

### ISSUE THREAD

**Issue by jtauber** [scott-fleischman/greek-grammar#12]
Here are two of the errors I found in SBLGNT text that Michael Holmes agreed were errors. I believe Rick fixed them somewhere but thought I'd just return the favour of your Luke fix and point these out:

βασιλεύς in Matt 27.37 (original SBLGNT had circumflex)
ὀνόματι in Romans 15.9 should have two acutes (original SBLGNT only had one and in the wrong place)

**Comment by scott-fleischman** [comment]
Thanks! I caught those when adding and aligning MorphGNT to our data. https://github.com/scott-fleischman/sblgnt-xml/commit/06f63fde89a94e159ed1a07e66cb199eb9e10546
